---
- name: download ohmyzsh-plugins
  ansible.builtin.git:
      repo: "https://github.com/{{ item.user }}/{{ item.repo }}"
      dest: "{{ ohmyzsh_custom_themes_folder }}/{{ item.repo }}"
      version: "{{ item.version | default('HEAD') }}"
      depth: 1
  loop: "{{ ohmyzsh_custom_themes }}"
